name: Build and run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt
    - run: pip install pyinstaller
    - run: pyinstaller main.spec
    - run: mv `ls -d dist/micro-minecraft-launcher*` dist/micro-minecraft-launcher
    - run: dist/micro-minecraft-launcher --version
